### ISSUE TITLE
Question about locks

### ISSUE THREAD

**Issue by goral09** [mozilla/rkv#122]
Hi, quick question. 

Why do `Read` and `Write` locks are taken on the `Rkv` environment instead of the `store`? It seems like although there can be multiple stores withing same environment, the locks are global. Does it mean that I cannot have two threads writing to different databases?

**Comment by mykmelez** [comment]
> Why do `Read` and `Write` locks are taken on the `Rkv` environment instead of the `store`?

This is due to the design of LMDB (the underlying storage engine for this Rust crate), which implements transactions at the level of the environment as a whole, not the individual database (a.k.a. store) within that environment.

For an environment with multiple stores whose data have relationships to each other, this design ensures that interdependent changes to multiple stores are atomic, and readers see a consistent view of the environment as a whole.

> It seems like although there can be multiple stores withing same environment, the locks are global. Does it mean that I cannot have two threads writing to different databases?

Yes, that's correct, you can never have more than one writer for an environment at any given time. If you try to create a writer while another writer is active, the call to create the second writer will block until the first writer is either committed or aborted.

Note, however, that you can have multiple writers writing to different environments. If you have two stores that you need to modify simultaneously on separate threads, and they're independent of each other (the data in one doesn't depend on the data in the other), then you could create separate environments for them, each of which can have one active writer and multiple readers at a time.

**Comment by goral09** [comment]
Thanks you for your comment mykmelez.

This answers my question. I have new one though - you talk about relations between stores. I have never heard of this concept before and I have spent some time researching LMDB internals. Can you tell me more or link to a resource?

**Comment by mykmelez** [comment]
> This answers my question. I have new one though - you talk about relations between stores. I have never heard of this concept before and I have spent some time researching LMDB internals. Can you tell me more or link to a resource?

It isn't a formal concept, as LMDB isn't a relational database, so there are no formal dependencies (such as foreign key constraints) between data in multiple stores. Nevertheless, an LMDB consumer might store related data in multiple stores and express those relationships in application code. And if it does so, then it will need to update multiple stores atomically in order to maintain data consistency.
